### ISSUE TITLE
Support for uploading file without "version"

### ISSUE THREAD

**Issue by ZHRen** [artipie/composer-adapter#83]
Example: https://github.com/aws/aws-sdk-php/blob/master/composer.json
This json file are lack of "version" key. When handling this minimal-package.json, the version() method in JsonPackage.class will throw error.
The version message maybe input by user when uploading. 
Composer.json is usually include in zip file, this is associate with this issue: https://github.com/artipie/composer-adapter/issues/23

**Comment by genryxy** [comment]
@ZHRen could you please clarify how this version is specified using with HTTP upload. Is this version passed as header? Or it would be better to specify an absent version in request line? Or something else?

**Comment by genryxy** [comment]
@ZHRen do I understand correct that `composer.json` which is uploaded as a file (not in zip file) always has `version` key, whereas `composer.json` which is included in archive usually does not have `version` key but version could be obtained, for example, from tgz file name?

**Comment by g4s8** [comment]
@genryxy what's the progress on this task?

**Comment by genryxy** [comment]
@ZHRen Integration test for uploading [ZIP archive](https://github.com/artipie/composer-adapter/blob/master/src/test/resources-binary/log-1.1.3.zip) without version in `composer.json` was added. 
Here are tests for installing uploaded file with [composer repo](https://github.com/artipie/composer-adapter/blob/master/src/test/resources-binary/log-1.1.3.zip) and with [artifacts repo](https://github.com/artipie/composer-adapter/blob/master/src/test/java/com/artipie/composer/http/HttpZipArchiveIT.java#L152). For `artifacts repo` it was necessary to add version in ZIP archive because otherwise it couldn't install.
Do you have some other cases for `composer.json` file without version? If not, I think this issue is no longer relevant
